### ISSUE TITLE
Upload error: VIdeo frame metadata could not be loaded

### ISSUE THREAD

**Issue by DataMonarch** [supervisely-ecosystem/import-videos-supervisely#7]
When uploading new video for the Video Labelling application, the mentioned error occurs. The test cases that I tried to pinpoint the problem:

- Behavior is account invariant: No matter what account I use, the same error is thrown
- I can reupload the videos that have already been uploaded before this behavior was encountered
- There is apparently nothing wrong with the metadata of the uploaded videos. I compared the metadata of the previously uploaded videos to the more recently recorded videos and could not find any difference. FYI, these videos were recorded under the same circumstances with the exact same hardware and was decoded using exactly the same Windows PC which has not been updated
- I tried uploading different videos, such as, videos downloaded from youtube, videos shot through the selfie camera of different laptops, and the rear camera of my OnePlus 9 pro. As a result, I faced the same error
- I tried adding a synthetic metadata stream to/ changing the per frame metadata of a video file which produced no favorable results.

! Important note: This software is an important part of our project and we need to get back on track with labelling ASAP. Please, look into the issue

![QnpMKfdxzw](https://user-images.githubusercontent.com/75782903/214039029-7e24a289-1a2d-4c0f-be14-ec76b9c76f68.png)

**Comment by cxnt** [comment]
Hi @DataMonarch! We are presently making improvements to this application, so your issue may have been resolved already and a fix will be released soon. 
In the meantime please try running  the app by choosing a different branch that might include a fix for your issue and let me know how it went

Please see launch instruction:
![launch](https://user-images.githubusercontent.com/48913536/214591333-15970ba1-ccf0-4592-8cd4-8ea23b981ed0.png)

**Comment by DataMonarch** [comment]
Thanks for your answer,
However, I am unable to see any branch other than master at the moment

**Comment by DataMonarch** [comment]
This is my usual workflow when uploading videos:

1. 
![image](https://user-images.githubusercontent.com/75782903/215267800-9b50f858-36c2-4c59-b7bf-2a17d518fa22.png)

2. 
![image](https://user-images.githubusercontent.com/75782903/215267827-849410e9-241b-4298-a243-18d2fd8a22f0.png)

With this method, I tried using the version 6 as well, but this approach did not lead me to a solution

I will try the automated upload using an agent from local directory, but I am not

**Comment by cxnt** [comment]
@DataMonarch Hi, you are using Supervisely plugins which are no longer maintained and will be removed very soon. You should use Supervisely apps instead.

For future video imports please use [Import Videos](https://ecosystem.supervise.ly/apps/import-videos-supervisely) app. Please try this method for importing new videos and let me know how it went or if you face any issues.

Here's the instruction for using this app:

1. Upload directory with videos to Team Files (START -> TEAM FILES) - just drag and drop directory into Team Files
2. Right click on the directory with videos in Team Files -> Run app -> Import -> Import Videos
3. Select options in the modal window and press the Run button. Your videos will be imported to selected project/dataset

As for the initial problem: you somehow managed to import video without metadata, we will investigate this case and get back to you on this matter

**Comment by cxnt** [comment]
@DataMonarch Hello, the metadata issue has been resolved, and you should now be able to open your videos. For the future imports please use Supervisely apps.
